linters:
  enable:
    - gofmt
    - nolintlint
    - errcheck
    - staticcheck
    - ineffassign
    - gosimple
    - unused
    - typecheck
    - govet

  disable:
    - gosec # false positives in CLI tool

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Allow ignoring errors with _ = in CLI context where fatal errors are already handled
    - path: 'cmd/'
      linters:
        - errcheck
      text: "Error return value of .json\\..* is not checked"
