package cmd

import (
	"fmt"
	"github.com/pterm/pterm"
	"github.com/spf13/cobra"
	"micli/miservice"
)

var (
	specCmd = &cobra.Command{
		Use:   "spec [model_keyword|type_urn]",
		Short: "MIoT Spec",
		Long:  `MIoT Spec`,
		Run: func(cmd *cobra.Command, args []string) {
			var (
				err     error
				keyword string
				res     interface{}
			)
			argLen := len(args)
			if argLen > 0 {
				keyword = args[0]
			} else {
				deviceMap := make(map[string]string)
				var devices []*miservice.DeviceInfo
				devices, err = getDeviceListFromLocal()
				choices := make([]string, len(devices))
				for i, device := range devices {
					choice := fmt.Sprintf("%s - %s", device.Name, device.Did)
					deviceMap[choice] = device.Model
					choices[i] = choice
				}
				choice, _ := pterm.DefaultInteractiveSelect.
					WithDefaultText("Please select a device").
					WithOptions(choices).
					Show()
				pterm.Info.Println("You choose: " + choice)
				keyword = deviceMap[choice]
			}
			//todo:完善spec
			var data *miservice.MiotSpecInstancesData
			data, err = srv.MiotSpec(keyword)
			if len(data.Services) > 0 {
				typeValue := data.Type
				info := fmt.Sprintf("# Generated by https://github.com/wangningkai/micli\n# More Detail: https://home.miot-spec.com/spec?type=%s", typeValue)
				pterm.Info.Println(info)
			}
			res = data

			handleResult(res, err)
		},
	}
)

func init() {
	specCmd.Example = "  spec\n  spec xiaomi.wifispeaker.lx06\n  spec urn:miot-spec-v2:device:speaker:0000A015:xiaomi-lx06:1"
}
