package cmd

import (
	"fmt"
	"strings"
	"unicode"

	"micli/pkg/miservice"

	"github.com/pterm/pterm"
	"github.com/pterm/pterm/putils"
	"github.com/samber/lo"
	"github.com/spf13/cobra"
)

var (
	specDetail bool
	specJSON   bool
)

var specCmd = &cobra.Command{
	Use:   "spec [?model_keyword|type_urn]",
	Short: "MIoT Spec",
	Long:  `MIoT Spec`,
	Run: func(cmd *cobra.Command, args []string) {
		var (
			err     error
			keyword string
		)
		argLen := len(args)
		if argLen > 0 {
			keyword = args[0]
		} else {
			deviceMap := make(map[string]string)
			var devices []*miservice.DeviceInfo
			devices, err = getDeviceListFromLocal()
			if err != nil {
				pterm.Error.Println(err.Error())
				return
			}
			choices := make([]string, len(devices))
			for i, device := range devices {
				choice := fmt.Sprintf("%s - %s", device.Name, device.Did)
				deviceMap[choice] = device.Model
				choices[i] = choice
			}
			choice, _ := pterm.DefaultInteractiveSelect.
				WithDefaultText("Please select a device").
				WithOptions(choices).
				Show()
			pterm.Info.Println("Choose Device: " + choice)
			keyword = deviceMap[choice]
		}
		var data *miservice.MiotSpecInstancesData
		data, err = ioSrv.MiotSpec(keyword)
		if err != nil {
			pterm.Error.Println(err.Error())
			return
		}

		// Extract model from type urn if needed
		model := keyword
		if strings.HasPrefix(keyword, "urn:miot-spec-v2:") {
			// Extract model from urn: format like urn:miot-spec-v2:device:speaker:0000A015:xiaomi-lx06:1
			parts := strings.Split(keyword, ":")
			if len(parts) >= 5 {
				model = parts[4]
			}
		}

		// Use detailed spec from home.miot-spec.com if --detail flag is set
		if specDetail {
			devSpec, err := ioSrv.GetDeviceInfo(model)
			if err != nil {
				pterm.Error.Println(err.Error())
				return
			}
			if specJSON {
				handleResult(devSpec, nil)
				return
			}
			// Output detailed tree with Chinese descriptions
			if len(devSpec.Services) > 0 {
				pterm.Info.Printf("Model: %s | Type: %s | %s\n", devSpec.Model, devSpec.Type, devSpec.DescZhCN)
				var leveledList pterm.LeveledList
				for _, service := range devSpec.Services {
					leveledList = append(leveledList, pterm.LeveledListItem{Level: 0, Text: fmt.Sprintf("%s (siid:%d)", pterm.Cyan(service.DescZhCN), service.Siid)})
					if len(service.Props) > 0 {
						leveledList = append(leveledList, pterm.LeveledListItem{Level: 1, Text: pterm.Magenta("属性 Properties")})
						for _, prop := range service.Props {
							detail := fmt.Sprintf("%s | %s (piid:%d, format:%s, access:[%s])", pterm.Green(prop.DescZhCN), prop.DescEn, prop.Piid, prop.Format, strings.Join(prop.Access, ","))
							leveledList = append(leveledList, pterm.LeveledListItem{Level: 2, Text: detail})
							if prop.ValueRange != nil && len(*prop.ValueRange) >= 2 {
								rangeData := fmt.Sprintf("range:[%v,%v], step:%v", (*prop.ValueRange)[0], (*prop.ValueRange)[1], (*prop.ValueRange)[2])
								leveledList = append(leveledList, pterm.LeveledListItem{Level: 3, Text: pterm.LightYellow(rangeData)})
							}
							if prop.ValueList != nil {
								for _, value := range prop.ValueList {
									leveledList = append(leveledList, pterm.LeveledListItem{Level: 3, Text: pterm.NewStyle(pterm.FgLightYellow).Sprintf("%d-%s|%s", value.Value, value.DescZhCN, value.DescEn)})
								}
							}
						}
					}
					if len(service.Actions) > 0 {
						leveledList = append(leveledList, pterm.LeveledListItem{Level: 1, Text: pterm.Magenta("动作 Actions")})
						for _, action := range service.Actions {
							leveledList = append(leveledList, pterm.LeveledListItem{Level: 2, Text: fmt.Sprintf("%s | %s (aiid:%d)", pterm.Green(action.DescZhCN), action.DescEn, action.Aiid)})
							if action.In != nil {
								for _, piid := range action.In {
									for _, prop := range service.Props {
										if prop.Piid == piid {
											leveledList = append(leveledList, pterm.LeveledListItem{Level: 3, Text: pterm.NewStyle(pterm.FgLightYellow).Sprintf("%d-%s", piid, prop.DescZhCN)})
											break
										}
									}
								}
							}
						}
					}
				}
				root := putils.TreeFromLeveledList(leveledList)
				root.Text = pterm.NewStyle(pterm.FgRed).Sprintf("设备规格 Device Spec [%s]", devSpec.DescZhCN)
				err = pterm.DefaultTree.WithRoot(root).Render()
				if err != nil {
					pterm.Error.Println(err.Error())
					return
				}
			}
			return
		}
		// https://miot-spec.org/miot-spec-v2/spec/service?type=
		// https://miot-spec.org/miot-spec-v2/spec/action?type=
		// https://miot-spec.org/miot-spec-v2/spec/property?type=
		if len(data.Services) > 0 {
			typeValue := data.Type
			info := fmt.Sprintf("# Generated by https://github.com/wangningkai/micli\n# More Detail: https://home.miot-spec.com/spec?type=%s\n# Json: https://miot-spec.org/miot-spec-v2/instance?type=%s", typeValue, typeValue)
			pterm.Info.Println(info)
			var leveledList pterm.LeveledList
			for _, service := range data.Services {
				piids := make(map[interface{}]string, len(service.Properties))
				leveledList = append(leveledList, pterm.LeveledListItem{Level: 0, Text: fmt.Sprintf("%s (siid:%d)", pterm.Cyan(service.Description), service.Iid)})
				if len(service.Properties) > 0 {
					leveledList = append(leveledList, pterm.LeveledListItem{Level: 1, Text: pterm.Magenta("Properties")})
					for _, property := range service.Properties {
						if property.Description == "" {
							types := strings.Split(property.Type, ":")
							if len(types) > 3 {
								property.Description = titleCase(strings.ReplaceAll(types[3], "-", " "))
							}
						}
						piids[property.Iid] = property.Description
						detail := fmt.Sprintf("%s (piid:%d,format:%s,access:[%s])", pterm.Green(property.Description), property.Iid, property.Format, strings.Join(property.Access, ","))
						leveledList = append(leveledList, pterm.LeveledListItem{Level: 2, Text: detail})
						if property.ValueRange != nil {
							min := property.ValueRange[0]
							max := property.ValueRange[1]
							step := property.ValueRange[2]
							rangeData := fmt.Sprintf("range:[%v,%v],step:%v", min, max, step)
							leveledList = append(leveledList, pterm.LeveledListItem{Level: 3, Text: pterm.LightYellow(rangeData)})
						}
						if property.ValueList != nil {
							for _, value := range property.ValueList {
								leveledList = append(leveledList, pterm.LeveledListItem{Level: 3, Text: pterm.NewStyle(pterm.FgLightYellow).Sprintf("%d-%s", value.Value, value.Description)})
							}
						}
					}
					if service.Actions != nil {
						leveledList = append(leveledList, pterm.LeveledListItem{Level: 1, Text: pterm.Magenta("Actions")})
						for _, action := range service.Actions {
							leveledList = append(leveledList, pterm.LeveledListItem{Level: 2, Text: fmt.Sprintf("%s (aiid:%d)", pterm.Green(action.Description), action.Iid)})
							if action.In != nil {
								for _, in := range action.In {
									p, _ := lo.Find(service.Properties, func(property *miservice.MiotSpecProperty) bool { return property.Iid == int(in) })
									leveledList = append(leveledList, pterm.LeveledListItem{Level: 3, Text: pterm.NewStyle(pterm.FgLightYellow).Sprintf("%v-%v", in, p.Description)})
								}
							}
						}
					}
				}
			}
			root := putils.TreeFromLeveledList(leveledList)
			root.Text = pterm.NewStyle(pterm.FgRed).Sprintf("Miot Spec [%s]", data.Description)

			err = pterm.DefaultTree.WithRoot(root).Render()
			if err != nil {
				pterm.Error.Println(err.Error())
				return
			}
		}
	},
}

func titleCase(s string) string {
	words := strings.Split(s, " ")
	for i, w := range words {
		if len(w) > 0 {
			runes := []rune(w)
			runes[0] = unicode.ToUpper(runes[0])
			words[i] = string(runes)
		}
	}
	return strings.Join(words, " ")
}

func init() {
	specCmd.Flags().BoolVar(&specDetail, "detail", false, "show detailed spec from home.miot-spec.com (with Chinese descriptions)")
	specCmd.Flags().BoolVar(&specJSON, "json", false, "output in JSON format")
	specCmd.Example = "  spec\n  spec xiaomi.wifispeaker.lx06\n  spec urn:miot-spec-v2:device:speaker:0000A015:xiaomi-lx06:1\n  spec --detail xiaomi.wifispeaker.lx06\n  spec --json --detail xiaomi.wifispeaker.lx06"
}
